/*
    see comment in OSGCOMUD.h

    This file is automatically generated by the build system,
    which tries to know what options are valid in what
    combinations. Avoid changing this file manually unless
    you know what you're doing.
*/

#define RomFileName "vMac.ROM"
#define kCheckSumRom_Size 0x00020000
#define kRomCheckSum1 0x4D1EEEE1
#define kRomCheckSum2 0x4D1EEAE1
#define kRomCheckSum3 0x4D1F8172
#define RomStartCheckSum 1
#define SaveDialogEnable 0
#define EnableAltKeysMode 0
#define VarFullScreen 1
#define WantInitFullScreen 0
#define MayFullScreen 1
#define MayNotFullScreen 0
#define WantInitMagnify 0
#define EnableMagnify 0
#define MyWindowScale 1
#define WantInitRunInBackground 0
#define WantInitNotAutoSlow 1
#define WantInitSpeedValue 0
#define WantEnblCtrlInt 0
#define WantEnblCtrlRst 0
#define WantEnblCtrlKtg 0
#define UseControlKeys 1
#define UseActvCode 0
#define EnableDemoMsg 0
