/*
    see comment in OSGCOMUD.h

    This file is automatically generated by the build system,
    which tries to know what options are valid in what
    combinations. Avoid changing this file manually unless
    you know what you're doing.
*/

#define MySoundEnabled 0

#define MySoundRecenterSilence 0
#define kLn2SoundSampSz 3

#define dbglog_HAVE 1
#define dbglog_Lag 1

#define WantAbnormalReports 0

#define NumDrives 6
#define NonDiskProtect 0
#define IncludeSonyRawMode 1
#define IncludeSonyGetName 1
#define IncludeSonyNew 0
#define IncludeSonyNameNew 0

//#define vMacScreenWidth 512
//#define vMacScreenHeight 384
#define vMacScreenWidth 400
#define vMacScreenHeight 240

#define vMacScreenDepth 0

#if vMacScreenWidth != 512
#define UseLargeScreenHack 1
#endif

#define kROM_Size 0x00020000

#define IncludePbufs 1
#define NumPbufs 4

#define EnableMouseMotion 1

#define IncludeHostTextClipExchange 0
#define EnableAutoSlow 0
#define EmLocalTalk 0

#define AutoLocation 0
#define AutoTimeZone 0
#define CurMacLatitude 0
#define CurMacLongitude 0
#define CurMacDelta 0
